version: '3.7'

services:
  main:
    container_name: main
    restart: always
    build:
      context: .
      target: development
    volumes:
      - ./:/usr/src/app/
      - type: bind
        source: ${CUSTOM_FILE_PATH}/.npmrc
        target: /root/.npmrc
    ports:
      - ${SERVER_PORT}:${SERVER_PORT}
      - 9229:9229
    command: npm run start:dev
    env_file:
      - .env
    networks:
      - local
    depends_on:
      - redis
      - postgres
  redis:
    container_name: redis
    image: redis:5
    networks:
      - local
  postgres:
    container_name: postgres
    image: postgres:12
    networks:
      - local
    environment:
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_DB: ${DB_DATABASE_NAME}
      PG_DATA: /var/lib/postgresql/data
    ports:
      - 5432:5432
    volumes:
      - pgdata:/var/lib/postgresql/data
  pgadmin:
    container_name: pgadmin_test
    image: dpage/pgadmin4:latest
    depends_on: [postgres]
    networks:
      - local
    environment:
      PGADMIN_DEFAULT_EMAIL: pgadmin@example.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    volumes:
      - pgadmin4:/var/lib/pgadmin
networks:
  local:
volumes:
  pgdata:
  pgadmin4:
